coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 0%
        threshold: 100%
    patch:
      default:
        target: 0%
        threshold: 100%
